[2024-02-05T23:41:54.485+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_date scheduled__2024-02-04T23:00:00+00:00 [queued]>
[2024-02-05T23:41:54.501+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_date scheduled__2024-02-04T23:00:00+00:00 [queued]>
[2024-02-05T23:41:54.502+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-05T23:41:54.536+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_date> on 2024-02-04 23:00:00+00:00
[2024-02-05T23:41:54.540+0000] {standard_task_runner.py:60} INFO - Started process 134 to run task
[2024-02-05T23:41:54.543+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_date', 'scheduled__2024-02-04T23:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmpd0m2nie5']
[2024-02-05T23:41:54.544+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask print_date
[2024-02-05T23:41:54.621+0000] {task_command.py:423} INFO - Running <TaskInstance: welcome_dag.print_date scheduled__2024-02-04T23:00:00+00:00 [running]> on host 86f40dfcaade
[2024-02-05T23:41:54.732+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_date' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T23:00:00+00:00'
[2024-02-05T23:41:54.733+0000] {logging_mixin.py:188} INFO - Today is 2024-02-05
[2024-02-05T23:41:54.733+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-05T23:41:54.745+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=welcome_dag, task_id=print_date, execution_date=20240204T230000, start_date=20240205T234154, end_date=20240205T234154
[2024-02-05T23:41:54.797+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-05T23:41:54.827+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
